### ISSUE TITLE
[feature request] parent deck of filtered deck

### ISSUE THREAD

**Issue by pihentagy** [sachingooo/anki-filtered-deck-by-tag#6]
I'd like an option, where you can choose the parnent deck of the freshly created deck.

thanks

**Comment by sachingooo** [comment]
Same parent deck every time or select the parent deck every time at time of creation? I worry that selecting the parent deck every time would be adding an extra click for every time this addon is used

**Comment by pihentagy** [comment]
For me it's same parent every time. (If it is possible to mass-move decks, then my apologies, and one can do it with a multiselect all created decks and move it, but in that case please tell me how :wink:)

**Comment by sachingooo** [comment]
Same parent deck every time is reasonable - can add a config option for it in the next version. 

(And you _can_ mass-move created decks! The browse screen left sidebar/deck explorer allows you to select multiple decks with Ctrl+Click and then drag and drop; you just need to have the select mode on next to the deck search bar in the sidebar)

**Comment by pihentagy** [comment]
Hm, with the version below, I cannot select multiple decks with Ctrl+Click, I don't understand why.

OMG, I need to press a button, before being able to do it :facepalm: 
![image](https://github.com/sachingooo/anki-filtered-deck-by-tag/assets/29916/97d263e4-7d5d-4f9c-a4fb-caa47a71ccb7)


```
Version ⁨24.04 (429bc9e1)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
```

**Comment by sachingooo** [comment]
Glad you figured it out!
